# This is a basic workflow to help you get started with Actions

name: Deploy Vue Project

# Controls when the workflow will run
on:
  # puhs到main分支时触发
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1.Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4
      
      # 2.安装nodejs环境
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17' # 根据你的项目调整 Java 版本
          distribution: 'temurin' # 使用 Eclipse Temurin 发行版
          cache: 'maven' # 缓存 Maven 依赖，加速构建
      # 2.2检查Maven版本
      - name: Check Maven version
        run: mvn -version

      # 3.打包项目
      - name: Build with Maven
        run: mvn clean package
    
      # 4.1部署jar包
      - name: Deploy to server via SSH
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}  # 服务器的IP或域名
          username: ${{ secrets.SSH_USER }}  # 登录服务器的用户名
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # 使用 GitHub Secrets 中的私钥
          source: "./flash-supermarket/target/flash-supermarket-0.0.1-SNAPSHOT.jar"  # 本地 dist 目录中的内容
          target: "/www/wwwroot"  # 服务器上的目标路径
          strip_components: 3
      
      - name: Write SSH private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
      
      - name: SSH to Remote Server and Deploy
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no "${{ secrets.SSH_USER }}"@"${{ secrets.SSH_HOST }}" << 'EOF'
          ./www/wwwroot/stop_8080.sh
          nohup java -jar flash-supermarket-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
          EOF
      
      - name: Cleanup SSH private key
        run: rm private_key.pem
